### ISSUE TITLE
Out of Memory Error when Fine-tuning SBERT with batch size of 128

### ISSUE THREAD

**Issue by guenthermi** [jina-ai/finetuner#588]
The bug occured with the following code (lower batch size, e.g., 64, works):

```python
import finetuner

# login to finetuner api
finetuner.login()

# create and submit finetuning job
sbert_run = finetuner.fit(
    model='sentence-transformers/msmarco-distilbert-base-v3',
    train_data='sbert_train_out_of_memory_error',
    epochs=3,
    batch_size=128,
    learning_rate=1e-6,
    cpu=False,
)

# show log messages
for msg in sbert_run.stream_logs():
    print(msg)
```

```bash
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/src/app/finetuner/runner/__main__.py", line 240, in <module>
    main()
  File "/usr/src/app/finetuner/runner/__main__.py", line 188, in main
    _tuned_modules = tuner.fit(
  File "/usr/src/app/finetuner/tuner/tuner.py", line 231, in fit
    self._fit(train_data, eval_data, epochs)
  File "/usr/src/app/finetuner/tuner/tuner.py", line 268, in _fit
    self._train(train_data)
  File "/usr/src/app/finetuner/tuner/tuner.py", line 376, in _train
    embeddings, ref_emb = self._run_models(inputs)
  File "/usr/src/app/finetuner/tuner/tuner.py", line 353, in _run_models
    embedding = run_torch_model(model, model_inputs)
  File "/usr/src/app/finetuner/utils.py", line 18, in run_torch_model
    return model(**tensor)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/accelerate/utils/operations.py", line 507, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "/usr/local/lib/python3.8/site-packages/torch/amp/autocast_mode.py", line 12, in decorate_autocast
    return func(*args, **kwargs)
  File "/usr/src/app/finetuner/commons/models/modules.py", line 124, in forward
    out = self._model(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/transformers/models/distilbert/modeling_distilbert.py", line 567, in forward
    return self.transformer(
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/transformers/models/distilbert/modeling_distilbert.py", line 345, in forward
    layer_outputs = layer_module(
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/transformers/models/distilbert/modeling_distilbert.py", line 283, in forward
    sa_output = self.attention(
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/transformers/models/distilbert/modeling_distilbert.py", line 212, in forward
    scores = torch.matmul(q, k.transpose(2, 3))  # (bs, n_heads, q_length, k_length)
RuntimeError: CUDA out of memory. Tried to allocate 768.00 MiB (GPU 0; 22.20 GiB total capacity; 19.86 GiB already allocated; 660.12 MiB free; 20.47 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

```

**Comment by bwanglzu** [comment]
seems we are reserving the correct GPU, total capcaity is 22.20 GB. it's wired to see with such as small batch we have OOM issue. maybe need some profiling of vram.

**Comment by bwanglzu** [comment]
can not reproduce this, will close for now
